### ISSUE TITLE
feature request: add button for --clean-cache

### ISSUE THREAD

**Issue by runboy93** [bkw777/mainline#81] opened 2021-02-26 08:06 UTC
Ones from Feb 23 are missing from list (they been available on database, kernel.ubuntu.com), but for some reason app itself doesn't list them, despite refresh and restart app?

Latest for 5.10 for example is 5.10.17 (has 5.10.18) on app, and for 5.11 is latest for 5.11 series (has 5.11.1)

App version 1.0.14

**Comment by aaronanderson** [comment] 2021-02-26 16:14
It appears the binary links on the Ubuntu Mainline Kernel site are broke. For instance, the summary of  [kernel 5.11 ](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11/) is in the historical format with kernel links at the top but the format of [kernel 5.11.2](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11.2/) contains build information and none of the subdirectories provide links to the binaries. 

I think we will need to wait for Canonical to fix the mainline site.

**Comment by rreinurm** [comment] 2021-03-05 20:11
I manually downloaded packages from [kernel 5.11.3](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.11.3/). At least for amd64 links were working, but list in tool is not updated yet.

**Comment by rreinurm** [comment] 2021-03-07 19:47
Kernel 5.11.4 has appeared to the list :)

**Comment by runboy93** [comment] 2021-04-01 11:41
Again same problem with 5.11.11, 5.10.27 and other kernels on same date.

It seems like app updates list, but they don't actually show on the list.

**Comment by bkw777** [comment] 2021-04-08 19:46
Any time you think kernels are missing, where all related packages built successfully that day and are all available on the web site, but not in the app, then try "mainline --clean-cache"

I myself just now had no 5.11.11 even after pressing refresh a few times. But "--clean-cache" and suddenly 5.11.11 appears.

I'll add a button for that in the UI, or maybe make the existing refresh button just do that every time, though that will be slow.

I think what must be happening is, our local cache gets updated when a given kernel has failed to build or not yet completed or something, and then later that kernel becomes all good, but our local cache already has a record for that kernel and skips it from now on.

That should be fixable by having the cache refresh routine check timestamps vs the web site or just re-scan all the index.html's regardless maybe. Putting this on TODO.

**Comment by heldchen** [comment] 2021-05-31 17:36
thanks, I was wondering the same. just now mainline jumped from showing 5.12.4 as being latest available straight to 5.12.8

I suspect the update-check can be configured to a larger interval to lower the chance of querying it just in the moment when they are uploading/preparing the new builds. I had it on a 2h interval when I experienced the large gap.

**Comment by bkw777** [comment] 2021-11-30 22:39
Dupe of #45

**Closed by bkw777** 2021-11-30 22:39 UTC
Labels: enhancement
