### ISSUE TITLE
Seems broken, mainline 1.0.15-2

### ISSUE THREAD

**Issue by ScarFez** [bkw777/mainline#148] opened 2022-08-17 22:46 UTC
Doesn't seem to work any more after 1.0.15

mainline --install-latest --yes
mainline 1.0.15
Distribution: Ubuntu Kinetic Kudu (development branch)
Architecture: amd64
Running kernel: 5.18.8-051808-generic
Fetching index from kernel.ubuntu.com...
OK
----------------------------------------------------------------------
Found installed: 5.18.8-051808.202206290850
----------------------------------------------------------------------
----------------------------------------------------------------------
Latest update: 5.19.2
Preparing to install '5.19.2'
sh: 1: cd: can't cd to /root/.cache/mainline/5.19.2
E: Installation completed with errors

**Comment by FauthD** [comment] 2022-08-18 10:49
Same here

**Comment by FauthD** [comment] 2022-08-18 11:03
The .cache/mainline only contains index.html, no subdirs.

I also experience The issue #147 (https://github.com/bkw777/mainline/issues/147). Looks like this is related.

**Comment by bkw777** [comment] 2022-08-18 17:45
Yep. Definitely dupe of #147 . Working on it there

**Closed by bkw777** 2022-08-18 17:45 UTC
Labels: duplicate
