### ISSUE TITLE
 linux-headers-5.15.12-051512-generic : Depends: libssl3 (>= 3.0.0~~alpha1) but it is not installable

### ISSUE THREAD

**Issue by stevezau** [bkw777/mainline#127] opened 2022-01-05 03:48 UTC
Hi,

I'm running Ubuntu 21.10 Impish. It seems I cannot install the latest kernels headers due to..

```
 linux-headers-5.15.12-051512-generic : Depends: libssl3 (>= 3.0.0~~alpha1) but it is not installable
```

It seem libssl3 3.0.0~~alpha1 might be part of experimental packages?

Not sure if this is expected?

**Comment by stevezau** [comment] 2022-01-05 04:30
I got around this by installing libssl3 from jammy https://packages.ubuntu.com/jammy/amd64/libssl3/download. 

Not sure if that was the right thing to do but it seems to work.

**Comment by bkw777** [comment] 2022-01-16 23:29
Useful knowledge and useful work-around, but it's not a problem in the app and nothing the app can or should do anything about.

Maybe this should be in a wiki page and have the main readme point to it for various things like this that come up all the time for different versions and different install targets.

I want to close the issue because it's not actually an issue, meaning there is no code change to make in the app, nothing to fix.
But it IS something pretty much every user needs to be told.
And yet, only for today. In some weeks or months, the main ubuntu version will update and this will no longer be a thing except for people not updtaed. So the main readme is the wrong place. So it seems like maybe it's own wiki page that can just grow and grow over time with all the similar quirks and work-arounds needed for all the various versions.

**Comment by JMLX42** [comment] 2022-01-17 12:03
> I want to close the issue because it's not actually an issue, meaning there is no code change to make in the app, nothing to fix.
>  But it IS something pretty much every user needs to be told.

It would be cool if the app could detect there is corresponding wiki page for a specific kernel. The app would then display the link to the wiki for that kernel version, and the wiki page would container this kind of workarounds.

**Comment by amedee** [comment] 2022-03-09 11:46
See this thread on AskUbuntu: https://askubuntu.com/questions/1389585/how-do-i-install-kernel-5-15-7-on-ubuntu-21-10-impish-indri/1396683#1396683, and later this week I will also publish an article on my blog (https://amedee.be)

**Comment by bkw777** [comment] 2022-03-09 13:44
> See this thread on AskUbuntu: https://askubuntu.com/questions/1389585/how-do-i-install-kernel-5-15-7-on-ubuntu-21-10-impish-indri/1396683#1396683, and later this week I will also publish an article on my blog (https://amedee.be)

This looks like the most correct way to address this I have seen so far. Thank you!

**Comment by amedee** [comment] 2022-03-11 13:18
I propose to close this issue, and to open a new issue for the purpose of creating a wiki page.
I even volunteer to make an initial draft for such a page. I've done all the heavy work of finding out the root cause and trying out different workarounds, so I might as well share that knowledge.

**Comment by bkw777** [comment] 2022-03-11 16:21
Fine by me. And I'll do some clean up in the readme and add a link.

Maybe create a help page and link to that from the readme and link to this from the help page. Or maybe this one is so universal right now that it should go right in the front readme. Or maybe there should be something organized by kernel version numbers or ranges, since these universal problems come and go and change over time.

**Comment by amedee** [comment] 2022-03-12 00:10
Here is my proposed doc for installing `libssl3`: https://github.com/amedee/mainline_wiki/commit/57064f1535eb5e519b957f76792cbdfccca493e1
Feel free to tweak it to your desire. :)

**Comment by bkw777** [comment] 2022-03-12 02:34
@stevezau please try https://github.com/bkw777/mainline/wiki/Install-libssl3
Thank you @amedee

**Comment by raulvasquez** [comment] 2022-03-23 17:27
> 

Option 1 does not work on focal due to the libc6 dependency.

**Comment by bkw777** [comment] 2022-03-29 07:54
Closing because this was never actually a mainline app bug. The kernel package maintainers updated how they build the kernel packages many months ago, and current kernel packages no longer support older systems.

The options are to update to at least Impish and then install libssl3 from Jammy on top of that, or try to selectively install even more packages onto older systems, or don't. Either way, it's nothing this app has any control over. We don't build the kernel packages, didn't create these dependencies, can't remove them, and they aren't an error.

Thanks again to @amedee for working out the selective/surgical update work-around.
https://github.com/bkw777/mainline/wiki/Install-libssl3

**Closed by bkw777** 2022-03-29 07:54 UTC
Labels: invalid, pending
