### ISSUE TITLE
misleading/confusing ui: appears to fail finding available kernels due to combination of config settings and current kernel build results

### ISSUE THREAD

**Issue by username227** [bkw777/mainline#147] opened 2022-08-15 10:49 UTC
Hi,
Sometime last night, the program stopped finding all of the available kernels. It only lists the kernels that are active or installed. I have no option to install any additional kernels other than these.

**Comment by craigcarnell** [comment] 2022-08-15 18:10
I have the same issue. Ubuntu 22.04.1

**Comment by thememelord8261** [comment] 2022-08-16 08:03
Same here. Pop!_OS 20.04

Might it be an issue with the Ubuntu kernel index, or something of the like?

**Comment by StatusCode404** [comment] 2022-08-16 08:05
Same thing happening to me on ubuntu 20.04

**Comment by thememelord8261** [comment] 2022-08-16 08:15
I just ran mainline in the terminal and it's showing me that I can install 5.19.1, which didn't show up in the GUI. not showing anything else though.

**Comment by StatusCode404** [comment] 2022-08-16 08:18
This is all I get...

`$ mainline --list
mainline 1.0.15
Distribution: Ubuntu 20.04.4 LTS
Architecture: amd64
Running kernel: 5.17.15-danglingpointer-zen3-optimised
Fetching index from kernel.ubuntu.com...
OK
----------------------------------------------------------------------
Found installed: 5.17.15-danglingpointer-zen3-optimised-1
Found installed: 5.17.11-danglingpointer-zen3-optimised-1
Found installed: 5.15.0-46.49~20.04.1
Found installed: 5.15.0.46.49~20.04.16
----------------------------------------------------------------------
----------------------------------------------------------------------

======================================================================
Available Kernels
======================================================================
5.17.15.3.1                      Installed
5.17.11.3.1                      Installed
5.15.0.46.49                     Installed
`

**Comment by StatusCode404** [comment] 2022-08-16 08:20
Basically doesn't show what is available from `$ mainline --list` command.

**Comment by thememelord8261** [comment] 2022-08-16 08:24
`$ mainline --install-latest` is what I ran. The kernel page is also up, so that doesn't seem to be the issue, I believe,

**Comment by thememelord8261** [comment] 2022-08-16 08:30
Just tried running some older versions and the same issue is occurring on them as well.

**Comment by tomsoutherland** [comment] 2022-08-16 09:16
Confirmed. Worked a day ago...

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

$ mainline --list
mainline 1.0.15
Distribution: Ubuntu 22.04.1 LTS
Architecture: amd64
Running kernel: 5.19.1-051901-generic
Fetching index from kernel.ubuntu.com...
OK
----------------------------------------------------------------------
Found installed: 5.15.0-43.46
Found installed: 5.15.0.46.46
Found installed: 5.15.0-46.49
Found installed: 5.19.1-051901.202208111238
----------------------------------------------------------------------
----------------------------------------------------------------------

======================================================================
Available Kernels
======================================================================
5.19.1                           Running
5.15.0.46.49                     Installed
5.15.0.46.46                     Installed
5.15.0.43.46                     Installed

**Comment by username227** [comment] 2022-08-16 11:01
I'd also point out that the command line utility, ubuntu-mainline-kernel.sh, still locates all of the kernels on the ubuntu page, so it must be specific to this program.

**Comment by thememelord8261** [comment] 2022-08-16 15:44
The strange thing is, there hasn't been a change to the program since July 6th, so maybe something got outdated somewhere?

**Comment by choiman1559** [comment] 2022-08-17 13:38
I tried to install the latest kernel using the command:

```
$ mainline --install 5.19.1

mainline 1.0.15
Distribution: Ubuntu 20.04.4 LTS
Architecture: amd64
Running kernel: 5.19.0-051900-generic
Fetching index from kernel.ubuntu.com...
OK
----------------------------------------------------------------------
Found installed: 5.17.5-051705.202204271406
Found installed: 5.19.0-051900.202207312230
Found installed: 5.4.0-81.91
----------------------------------------------------------------------
----------------------------------------------------------------------
Preparing to install '5.19.1'
sh: 1: cd: can't cd to /home/cuj1559/.cache/mainline/5.19.1
E: Installation completed with errors

```

and my `/home/cuj1559/.cache/mainline` folder's structure is...

```
index.html
6.0.0-rc1 (folder)
    L> CHANGES
    L> index.html
    L> invaild
```

I think the problem is something is wrong with `mainline` parsing index.html.

Have canonical changed the html source of the ubuntu kernel-ppa site? If so, I think this is the cause.

**Comment by jadeops** [comment] 2022-08-17 16:53
Yup, seems like something is broken. 

Thanks for recommending `ubuntu-mainline-kernel.sh` I have switched to it for now https://github.com/pimlie/ubuntu-mainline-kernel.sh It seems to work fine even though last commit was on 9 Dec 2020 Feels like a nice minimal alternative.

About this repo, after clearing cache and checking for updates, the mainline index is empty? Either the downloader/parser is broken or Ubuntu server may be blocking the HTTP requests from this tool?
```
mainline --clean-cache
mainline --check
ls ~/.cache/mainline
```

**Comment by StatusCode404** [comment] 2022-08-18 09:05
@bkw777 hi mate, just checking if you're still supporting this project?  It is currently failing to work as intended.

**Comment by FauthD** [comment] 2022-08-18 10:51
Same here, even with a fresh Kubuntu 22.04.01 install

**Comment by bkw777** [comment] 2022-08-18 17:41
Something changed in the last couple days. I just installed 5.19.1 only a day or so ago myself. The source url is up so either the index.html changed or possibly something about aria2c changed, but "aria" doesn't appear in /var/log/dpkg.log at all which goes back to 08-01 before the breakage. So the site changed the index.html in a way that the parser now fails on. I'm looking into it.

**Comment by bkw777** [comment] 2022-08-18 18:08
At first glance it looks like the regex should still be working. There is a non-empty, fresh index.html in my ~/.cache/mainline, and in it are hrefs that look just like the regex and the sample in the comments in https://github.com/bkw777/mainline/blob/master/src/Common/LinuxKernel.vala#L363
(along the way I see that sample url in the comment exposes that the history on the mainline-ppa site is incomplete. Where did 3.0.x-oneiric go?) Oh well, adding more debugging...

**Comment by bkw777** [comment] 2022-08-18 21:49
OK TLDR: for now, work-around, increase the config etting "show previous N majors" to at least 1.

Explaination
It's a non-obvious combination of more or less legit factors combining to make it look worse than it is.

The worst factor is I don't have good enough display of what's going on in the app. It just does stuff and when it doesn't include a kernel in the list, it doesn't show the user why. I think a TODO for that would be some sort of immediate display toggle to show/hide all the invalid kernels, so that you could quickly make all the invalid kernels appear, greyed-out, but with tooltips or clickable popups to say why each one was disabled. IE, failed build, doesn't meet settings filters etc.

Aside from that, in the current case what's going on is there is a new major version with only a single kernel yet,
So when show_previous_majors=0, all the 5.x are hidden and the only thing considered is the single new 6.x

Annnnd that one happens to be a failed build, so it is not shown.
```
Test amd64/build failed (rc=2, on=amd64, time=0:06:31, log=[amd64/log](https://kernel.ubuntu.com/~kernel-ppa/mainline/v6.0-rc1/amd64/log))

Test amd64/self-tests failed (rc=2, on=amd64, time=0:00:16, log=[amd64/self-tests/log](https://kernel.ubuntu.com/~kernel-ppa/mainline/v6.0-rc1/amd64/self-tests/log))
```

Aaaaaand 5.19.2 which just appeared last night also happens to be a failed build.

It's just a fluke combination of conditions.

I'm going to think on this a bit and I'm not closing the issue immediately, because I'm not sure there isn't still some corner case problem with the version comparison logic. For instance, If you UN-select "show unstable", then really that major version should not be considered for the comparison math if there are no non-rc kernels in that new major version yet. In which case, with "show unstable" deselected, it should show all the 5.x, instead of the 6.x but it doesn't do that right now. So, there's some things to improve about the new version switchover condition.

But anyway there you are. As soon as a 6.x appears that isn't a failed build, then you'll see it. Or just increase N previous from 0 to 1 and you'll get all the 5.x back, but still not the latest 5.19.2 because it's a failed build.

**Comment by bkw777** [comment] 2022-08-18 22:07
Huh... 5.19.2 still shows up, because although the self-test failed, all the package builds suceeded, at least for the client platform amd64.
By rights I think I should be hiding that kernel in that case but I'll leave it for now.

**Comment by username227** [comment] 2022-08-19 01:20
I can confirm that changing this setting did work. Thanks for looking into this. And we appreciate all of your work on this!

**Comment by bkw777** [comment] 2022-08-19 23:43
Maybe both of the display settings should actually be buttons right on the main display not hidden away in a settings screen. That thing to hide old versions could be much more obvious if just done some other way.

Maybe for hiding old versions, the main list could be a collapsed tree with just major version numbers one per line, with only the highest version expanded by default.

Then, when a time like this week comes along, the display would be more intuitive. Instead of going completely empty like this week, it would just go down to 6 collapsed top-level entries, and it would be intuitive and natural for the user to try expanding them and see all the 5.x still there. That would actually remove the need for that show N previous majors setting to even exist. It's only there to keep the main list from including 9 million kernels no one cares about. A single collapsed entry for all the 2.x for instance would be fine to just be there all the time. We're only up to 6 after 28 years.

And the hide-rc could be some form of direct ui toggle not a setting.

**Closed** 2022-08-21 01:08 UTC

**Comment by craigcarnell** [comment] 2022-08-21 14:55
I've updated to the latest version however after selecting Kernel 5.19.2 on a clean Ubuntu 22.04.1 install it reboots with:

"error: bad shim signature.
error: you need to load the kernel first.

Press any key to continue..."

**Comment by bkw777** [comment] 2022-08-23 22:38
You can put show_previous_N_majors back to 0 if you want as of v1.0.16

**Comment by jagiella** [comment] 2022-09-18 09:37
for me updating to v1.0.16 did not solve the problem

![image](https://user-images.githubusercontent.com/4679834/190895737-fa5c381f-844d-4f9d-83f9-c16472c7f75c.png)

**Comment by bkw777** [comment] 2022-09-18 19:36
You have to say more than that if you want any help. Did you try clearing cache? Where is the screenshot from running with debug turned on? Since it works for me, and since you didn't provide any info, it could be a network problem for all I know.

**Comment by jagiella** [comment] 2022-09-22 09:02
```bash
$ mainline --clean-cache
mainline 1.0.16
Distribution: Ubuntu Kinetic Kudu (development branch)
Architecture: amd64
Running kernel: 5.19.0-15-generic
Removed cached files in '/home/nickj/.cache/mainline'
```

```bash
$ mainline-gtk --debug
mainline 1.0.16
Distribution: Ubuntu Kinetic Kudu (development branch)
Architektur: amd64
Running kernel: 5.19.0-15-generic
D: query_thread() App.show_prev_majors: 0
D: query_thread() App.hide_unstable: false
D: file_parent(/home/nickj/.cache/mainline/index.html)
D: dir_create(/home/nickj/.cache/mainline)
D: Erstelltes Verzeichnis: /home/nickj/.cache/mainline
D: dir_create(/tmp/.mainline_PZ63utzc)
D: Erstelltes Verzeichnis: /tmp/.mainline_PZ63utzc
D: build_script():
D: working_dir=/tmp/.mainline_PZ63utzc
D: file_write(/tmp/.mainline_PZ63utzc/download.list)
D: file_parent(/tmp/.mainline_PZ63utzc/download.list)
D: dir_create(/tmp/.mainline_PZ63utzc)
D: Datei gespeichert:/tmp/.mainline_PZ63utzc/download.list
D: aria2c --no-netrc true -i '/tmp/.mainline_PZ63utzc/download.list' --show-console-readout=false --summary-interval=1 --auto-save-interval=1 --human-readable=false --enable-color=false --allow-overwrite --connect-timeout=15 --timeout=60 --max-concurrent-downloads=4 --max-file-not-found=3 --retry-wait=2
D: save_bash_script_temp(/tmp/.mainline_PZ63utzc/script.sh):/tmp/.mainline_PZ63utzc/script.sh
D: file_write(/tmp/.mainline_PZ63utzc/script.sh)
D: file_parent(/tmp/.mainline_PZ63utzc/script.sh)
D: dir_create(/tmp/.mainline_PZ63utzc)
D: Datei gespeichert:/tmp/.mainline_PZ63utzc/script.sh
D: AsyncTask:begin():try
D: working_dir=/tmp/.mainline_PZ63utzc
Holt den Index von kernel.ubuntu.com...
D: AsyncTask:finish(): before finish_task()
D: dir_delete():Gelöscht: /tmp/.mainline_PZ63utzc
OK
D: highest_maj = 6
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc6/index.html)
D: file_basename(/home/nickj/.cache/mainline/6.0.0-rc6/index.html)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc6/CHANGES)
D: file_basename(/home/nickj/.cache/mainline/6.0.0-rc6/CHANGES)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc5/index.html)
D: file_basename(/home/nickj/.cache/mainline/6.0.0-rc5/index.html)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc5/CHANGES)
D: file_basename(/home/nickj/.cache/mainline/6.0.0-rc5/CHANGES)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc4/index.html)
D: file_basename(/home/nickj/.cache/mainline/6.0.0-rc4/index.html)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc4/CHANGES)
D: file_basename(/home/nickj/.cache/mainline/6.0.0-rc4/CHANGES)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc3/index.html)
D: file_basename(/home/nickj/.cache/mainline/6.0.0-rc3/index.html)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc3/CHANGES)
D: file_basename(/home/nickj/.cache/mainline/6.0.0-rc3/CHANGES)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc2/index.html)
D: file_basename(/home/nickj/.cache/mainline/6.0.0-rc2/index.html)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc2/CHANGES)
D: file_basename(/home/nickj/.cache/mainline/6.0.0-rc2/CHANGES)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc1/index.html)
D: file_basename(/home/nickj/.cache/mainline/6.0.0-rc1/index.html)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc1/CHANGES)
D: file_basename(/home/nickj/.cache/mainline/6.0.0-rc1/CHANGES)
D: dir_create(/tmp/.mainline_uYTWrvK7)
D: Erstelltes Verzeichnis: /tmp/.mainline_uYTWrvK7
D: build_script():
D: working_dir=/tmp/.mainline_uYTWrvK7
D: file_write(/tmp/.mainline_uYTWrvK7/download.list)
D: file_parent(/tmp/.mainline_uYTWrvK7/download.list)
D: dir_create(/tmp/.mainline_uYTWrvK7)
D: Datei gespeichert:/tmp/.mainline_uYTWrvK7/download.list
D: aria2c --no-netrc true -i '/tmp/.mainline_uYTWrvK7/download.list' --show-console-readout=false --summary-interval=1 --auto-save-interval=1 --human-readable=false --enable-color=false --allow-overwrite --connect-timeout=15 --timeout=60 --max-concurrent-downloads=4 --max-file-not-found=3 --retry-wait=2
D: save_bash_script_temp(/tmp/.mainline_uYTWrvK7/script.sh):/tmp/.mainline_uYTWrvK7/script.sh
D: file_write(/tmp/.mainline_uYTWrvK7/script.sh)
D: file_parent(/tmp/.mainline_uYTWrvK7/script.sh)
D: dir_create(/tmp/.mainline_uYTWrvK7)
D: Datei gespeichert:/tmp/.mainline_uYTWrvK7/script.sh
D: AsyncTask:begin():try
D: working_dir=/tmp/.mainline_uYTWrvK7

Index abrufen...

░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0 % D: AsyncTask:finish(): before finish_task()
D: dir_delete():Gelöscht: /tmp/.mainline_uYTWrvK7
▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100 % 

D: file_write(/home/nickj/.cache/mainline/6.0.0-rc6/invalid)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc6/invalid)
D: dir_create(/home/nickj/.cache/mainline/6.0.0-rc6)
D: Datei gespeichert:/home/nickj/.cache/mainline/6.0.0-rc6/invalid
D: file_write(/home/nickj/.cache/mainline/6.0.0-rc5/invalid)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc5/invalid)
D: dir_create(/home/nickj/.cache/mainline/6.0.0-rc5)
D: Datei gespeichert:/home/nickj/.cache/mainline/6.0.0-rc5/invalid
D: file_write(/home/nickj/.cache/mainline/6.0.0-rc4/invalid)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc4/invalid)
D: dir_create(/home/nickj/.cache/mainline/6.0.0-rc4)
D: Datei gespeichert:/home/nickj/.cache/mainline/6.0.0-rc4/invalid
D: file_write(/home/nickj/.cache/mainline/6.0.0-rc2/invalid)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc2/invalid)
D: dir_create(/home/nickj/.cache/mainline/6.0.0-rc2)
D: Datei gespeichert:/home/nickj/.cache/mainline/6.0.0-rc2/invalid
D: file_write(/home/nickj/.cache/mainline/6.0.0-rc1/invalid)
D: file_parent(/home/nickj/.cache/mainline/6.0.0-rc1/invalid)
D: dir_create(/home/nickj/.cache/mainline/6.0.0-rc1)
D: Datei gespeichert:/home/nickj/.cache/mainline/6.0.0-rc1/invalid
D: highest_maj = 6
D: check_installed()
----------------------------------------------------------------------
D: query_installed_packages()
D: dir_create(/tmp/.mainline_hA76RXx5)
D: Erstelltes Verzeichnis: /tmp/.mainline_hA76RXx5
D: file_write(/tmp/.mainline_hA76RXx5/1663837323451021737)
D: file_parent(/tmp/.mainline_hA76RXx5/1663837323451021737)
D: dir_create(/tmp/.mainline_hA76RXx5)
D: Datei gespeichert:/tmp/.mainline_hA76RXx5/1663837323451021737
D: Datei Gelöscht: /tmp/.mainline_hA76RXx5/1663837323451021737
D: dir_delete():Gelöscht: /tmp/.mainline_hA76RXx5
Found installed: 5.19.0-15.15
D: Package: linux-image-5.19.0-15-generic
D: Package: linux-modules-5.19.0-15-generic
Found installed: 5.19.5-051905.202208291036
D: Package: linux-headers-5.19.5-051905
D: Package: linux-headers-5.19.5-051905-generic
D: Package: linux-image-unsigned-5.19.5-051905-generic
D: Package: linux-modules-5.19.5-051905-generic
Found installed: 5.19.0.17.17
D: Package: linux-generic
D: Package: linux-image-generic
D: Package: linux-headers-generic
Found installed: 5.19.0-17.17
D: Package: linux-modules-5.19.0-17-generic
D: Package: linux-headers-5.19.0-17
D: Package: linux-headers-5.19.0-17-generic
D: Package: linux-image-5.19.0-17-generic
D: Package: linux-modules-extra-5.19.0-17-generic
D: Package: linux-libc-dev
----------------------------------------------------------------------
----------------------------------------------------------------------
D: check_updates()
D: tv_refresh()
```

![image](https://user-images.githubusercontent.com/4679834/191705432-4a7d0a17-4485-467a-9118-34e632c88295.png)
