### ISSUE TITLE
issues with kernel 5.11.8 and up and kernel 5.12.* onwards

### ISSUE THREAD

**Issue by clived2** [bkw777/mainline#89] opened 2021-05-04 01:39 UTC
I am a long time Ubuntu user (now at Ubuntu 20.04. I have been using the mainline kernels for about a year and never had any problems until the last month or so. From kernel 5.11.8 up do what I am currently running (5.11.18), all the releases I have ended up with dependencies after I installed the code which fortunately 9 knew how to fix using the apt-get command, and on the kernel 5.12.0 and up the same issue which I was unable to understand to fix. I am running on an older Dell Optiplex 760 with 4 gigs of ram and a 200 meg hdd. My other computer is a HPG60 notebook with 200 meg hdd and 3 megs ram. Both are using Ubuntu 20.04. I am getting the same problems on both systems. 

Just thought that I would pass this onto you folks, in case someone on your end is aware of this issue.

Clive DaSilva

**Comment by szymonrychu** [comment] 2021-05-18 12:53
I believe it's the same for newer machines too.
On 2019 XPS13 running latest linux Mint the problem occurs too.

At the same time I suspect it's possible that it's not a problem with the `mainline` tool itself.

**Comment by lazystone** [comment] 2021-05-20 10:25
That might be:

* https://bugs.launchpad.net/umkl/+bug/1927024
* https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1926938

**Comment by bkw777** [comment] 2021-08-20 01:52
dupe of #87

**Closed by bkw777** 2021-08-20 01:52 UTC
Labels: duplicate
